name: WorkFlow to publish research papers and  fetch google sheets
run-name: ${{ github.actor }} is fetching google sheets
on: #[push]
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  FetchGoogleSheets:
    runs-on: ubuntu-latest
    steps:
      # - name: create-json
      #   uses: actions/checkout@v1
      #   run: |
      #       echo "Publishing Research Papers"
      #       python fetchXML.py
      #       echo "Completed Publishing Research Papers"
      - run: echo "This job was automatically triggered by a ${{github.event_name}} event."
      # - name: Fetch Google Sheets
      #   uses: actions/checkout@v1
      #   run: |
      #       echo "Fetching Google Sheets Data"
      #       python accessGoogleSheets.py
      #       echo "Completed Work Flow"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - run: |
            pip install oauth2client
            pip install gspread
            echo "Fetching Google Sheets Data"
            python accessGoogleSheets.py
            echo "Completed Work Flow"
  FetchResearchPaper:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{github.event_name}} event."
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.10' 
      - run: |
            pip install oauth2client
            pip install gspread
            pip install requests
            echo "Fetching Research Papers Data"
            python fetchXML.py
            echo "Completed Work Flow"