name: WorkFlow to publish research papers and  fetch google sheets
run-name: ${{ github.actor }} is fetching google sheets
on: #[push]
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  FetchGoogleSheets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install oauth2client
          pip install gspread

      - name: Fetch Google Sheets Data
        run: python accessGoogleSheets.py

      - name: Complete Workflow
        run: echo "Completed Workflow"
        
      - name: Update researchPapers.csv
        run: |
          # cp output/researchPapers.csv _data/researchers/sheets/researchPapers.csv
          # git add _data/researchers/sheets/researchPapers.csv
          git config user.name "nagarajumadamshetti"
          git config user.email "nagarajumadamshetti@gmail.com"
          git diff
          # git commit -m "Update researchPapers.csv"
          # git push
  # FetchResearchPaper:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "This job was automatically triggered by a ${{github.event_name}} event."
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4 
  #       with:
  #         python-version: '3.10' 
  #     - run: |
  #           pip install oauth2client
  #           pip install gspread
  #           pip install requests
  #           echo "Fetching Research Papers Data"
  #           python fetchXML.py
  #           echo "Completed Work Flow"